apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deployment-repo.fullname" . }}
  labels:
    app: {{ include "deployment-repo.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "deployment-repo.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "deployment-repo.name" . }}
    spec:
      containers:
        - name: {{ include "deployment-repo.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}









































